#!/bin/sh

start() {
   echo "Start"
}

stop() {
   echo "Stop"
}

restart() {
   stop
   start
}

status() {
   echo "Status"
}

info(){
   echo "Usage: $NAME {start|stop|restart|status}"
}

case "$1" in 
   start)
      start
      ;;

   stop)
      stop
      ;;

   restart)
      restart
      ;;

   status)
      status
      ;;

   *)
      info
esac
 
exit 0
